# Generated by Django 3.2.1 on 2021-05-04 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'db_table': 'Metrics',
            },
        ),
    ]
