# Generated by Django 3.2 on 2021-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=1024)),
                ('pageURL', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.AlterField(
            model_name='metrics',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
